---

# <center>Medidas de Resumo</center>

---

## <strong style="color: #800000;">Medidas de Posição - Dados não agrupados🦉</strong>

<p style="font-family: 	Times New Roman; font-size: 16px;">Medidas de posição são medidas que nos permitem representar de forma resumida um conjunto de dados relacionados a um determinado fenômeno.</p>

---

### Média

<p style="font-family: 	Times New Roman; font-size: 16px;">Seja $X$ a variável de estudo, $x_i$ representa o valor observado na n-ésima unidade experimental e $\bar{X}$ é a sua média. Quando os dados são não agrupados a sua média é dada pela soma de todos os elementos dividido pelo número de elementos.</p>

### $$\bar{X} = \frac{1}{n}\sum_{i=1}^nx_i$$

In [1]:
def media(X):
    """
        Cálcular a média da variável X.
    """
    
    # Somando todos os elementos 
    s = sum(X)
    
    # Obtendo o número de elementos da variável X
    n = len(X)
    
    # Cálculo da média
    md = s / n
    
    # Imprimindo o resultado da média
    print(f"Média: {md:.2f}")

In [2]:
# Chamando a função media
media([1, 2, 3, 4, 5])

Média: 3.00


**Segunda opção para o calculo da média**

In [3]:
import pandas as pd
import numpy as np
import warnings

# Removendo Alertas Indesejáveis
warnings.filterwarnings("ignore")

In [4]:
# Cálculo da média
np.mean([1, 2, 3, 4, 5])

3.0

---

### Mediana

<p style="font-family: 	Times New Roman; font-size: 16px;">A mediana ($Me$ ou $Md$) de uma variável $X$ é dada pelo valor que divide ao meio, ou seja, é o valor (do próprio conjunto ou teórico) que tem antes e depois de si igual quantidade de dados.</p>

### $$Md(X) = X_{(\frac{n+1}{2})}, Ímpar$$

### $$Md(X) = \frac{X_{(\frac{n}{2})} + X_{(\frac{n}{2}+1)}}{2}, Par$$

In [5]:
def mediana(X):
    
    # Rol da variável X
    X_ordenado = sorted(X)
    
    # Codição para o cálculo correto da mediana
    n = len(X)
    if(n % 2 == 0):
        # Cálculo da mediana
        me = ((X[int((n/2))] + X[int(((n/2) + 1))]) / 2) - 1
    else:
        me = X[int(((n + 1) / 2))-1]
        
    # Imprimindo o valor da mediana
    print(f"Mediana: {me:.2f}")

In [6]:
# Chamando a função mediana
mediana([1, 2, 3, 4, 5]) # n Ímpar
mediana([1, 2, 3, 4, 5, 6, 7, 8]) # n Par

Mediana: 3.00
Mediana: 4.50


**Segunda opção para o cálculo da mediana**

In [7]:
np.median([1, 2, 3, 4, 5, 6, 7, 8])

4.5

---

### Moda

<p style="font-family: 	Times New Roman; font-size: 16px;">A moda $Mo$ de uma variável $X$ é o valor que mais se repete no conjunto de dados.</p>

<p><strong>Mo</strong> - Valor com maior $f_i$</p>

In [8]:
from scipy import stats as st

In [9]:
# Cálculando a moda com o pacote Scipy
l = [1, 2, 2, 3, 1, 2, 5, 4, 4, 3, 2]
print("Vetor: ", l)
print(f"Moda: {st.mode(l)[0][0]}")

Vetor:  [1, 2, 2, 3, 1, 2, 5, 4, 4, 3, 2]
Moda: 2


## <strong style="color: #800000;">Medidas de Posição - Dados agrupados sem intervalo de classe  🦘</strong>

---

### Média

<p style="font-family: 	Times New Roman; font-size: 16px;">Seja $X$ a variável em estudo, $x_i$ representa o valor observado da variável na i-ésima unidade experimental e $\bar{X}$ é a sua média.</p>


### $$\bar{X} = \frac{\sum x_if_i}{\sum fi}$$

### Mediana

<p style="font-family: 	Times New Roman; font-size: 16px;">A mediana ($M_e$) de uma variável X é dada pelo valor que divide o conjunto de dados ao meio, ou seja, é o valor (do próprio conjunto ou teórico) que tem antes e depois de si igual quantidade de dados. No caso de dados agrupados sem intervalo de classe, precisamos calcular a frequência acumulada ($F_{ac}$) e o valor $\frac{n}{2}$ o qual divide o conjunto de dados ao meio. Busca-se o valor $\frac{n}{2}$ na $F_{ac}$ e determina-se qual é a classe que representa a mediana.</p>

### Moda

<p style="font-family: 	Times New Roman; font-size: 16px;">A moda ($M_o$) de uma variável X é dado pelo valor que apresenta a maior frequência absoluta, ou seja, é o valor que mais se repete no conjunto de dados.</p>

### $$M_o = Maior f_i$$

## <strong style="color: #800000;">Medidas de Posição - Dados agrupados com intervalo de classe  🦩</strong>

### Média

<p style="font-family: 	Times New Roman; font-size: 16px;">Para dados agrupados com intervalos de classe é necessário calcular para cada classe o ponto médio dado por $x_i = \frac{l_i + l_s}{2}$ e depois pode-se proceder da mesma forma que para dados agrupados sem intervalos de classe.</p>

### $$\bar{X} = \frac{\sum x_if_i}{\sum fi}$$

### Mediana

<p style="font-family: 	Times New Roman; font-size: 16px;">Busca-se o valor $\frac{n}{2}$ e determina-se qual é a classe que representa a mediana. Após ser determinada a classe que contém a mediana, aplica-se a seguinte equação:</p>

### $$M_e(X) = l_{iMe} + \left[\frac{\frac{n}{2} - \sum f_{iant}}{f_{iMe}}\right]h$$

Onde:

- $l_{iMe}$ - Limite inferior da classe que contém a mediana.

- $\sum f_{iant}$ - Soma das frequências anteriores à classe da mediana.

- $f_{iMe}$ - Frequência da classe que contém a mediana.

- $h$ - Amplitude do intervalo de classe.

### Moda

<p style="font-family: 	Times New Roman; font-size: 16px;">A moda $M_o$ de uma variável $X$ é dada pelo valor que apresenta maior frequência absoluta, ou seja, é o valor que mais se repete no conjunto de dados. Desta forma determina-se a classe com maior e aplica-se a fórmula abaixo:</p>

### $$M_o(X) = l_{iMo} + \left[ \frac{\Delta_1}{\Delta_1 + \Delta_2}\right]h$$

Onde:

- $l_{iMo}$ - Limite inferior da classe que contém a moda.

- $\Delta_1 = f_{iMo} - f_{iant}$: Frequência da classe da moda menos a frequência da classe anterior a da moda.

- $\Delta_2 = f_{iMo - f_{ipos}}$: Frequência da classe da moda menos a frequência da classe posterior a da moda.

- $h$ - Amplitude do intervalo de classe.

## Exemplo - Python  🐑

<p style="font-family: 	Times New Roman; font-size: 16px;">O conjunto de dados abaixo representa a altura em centímetros de uma turma de alunos do ensino médio:</p>

---

160, 160, 162, 163, 163,
165, 167, 168, 170, 170,
171, 172, 174, 174, 175,
177, 178, 178, 178, 180

---

**O nosso objetivo é construir uma tabela de distribuição de frequências para dados agrupados com intervalo de classe.**

In [10]:
# Instanciando os valores das alturas dos alunos
alturas = [160, 160, 162, 163, 163, 165, 167, 168, 170, 170,
           171, 172, 174, 174, 175, 177, 178, 178, 178, 180]

### Definindo o número de classes com a regra de sturges

### $$k = 1 + 3,3log_{10}(n)$$

In [11]:
# Aplicando a regra de Sturgues
k = round(1 + (3.3 * np.log10(len(alturas))))

# Imprimindo o número de intervalos 
print(f'Número de intervalos de classe: {k}')

Número de intervalos de classe: 5


### Obtendo a Amplitude de Classe

<p style="font-family: 	Times New Roman; font-size: 16px;">Para obtermos a amplitude de classe ($h$), é necessário obter antes a amplitude total ($Altura_{max} - Altura_{min}$). Em seguida dividimos a amplitude total ($AT$) pelo número de classes ($k$), obtida através da regra de Sturges.</p>

In [12]:
# Amplitude Total
AT = max(alturas) - min(alturas)
print(f"Amplitude Total {AT}")

Amplitude Total 20


In [13]:
# Amplitude de classe
h = AT / k

# Imprimindo a amplitude de classe
print(f'Amplitude de Classe: {h}')

Amplitude de Classe: 4.0


### Criando a Tabela de Frequências Com Intervalo De Classe

- $fi = $ Frequência Absoluta

- $fri = $ Frequência Relativa

- $fac = $ Frequência Acumulada

- $xi = $ Ponto Médio

In [14]:
# Dados da tabela de frequências
classes = ["160 |-- 164", "164 |-- 168", "168 |-- 172", "172 |-- 176", "176 --| 180"]
fi      = [5, 2, 4, 4, 5]
fri     = [0.25, 0.10, 0.20, 0.20, 0.25]
fac     = [5, 7, 11, 15, 20]
xi      = [162, 166, 170, 174, 178]
df_dict = {
           "fi":  fi,
           "fri": fri,
           "fac": fac,
           "xi":  xi
}

# Criando Tabela de Frequências 
df = pd.DataFrame(df_dict, index=classes)

# Imprimindo a tabela de Frequências
df

fi   fri  fac   xi
160 |-- 164   5  0.25    5  162
164 |-- 168   2  0.10    7  166
168 |-- 172   4  0.20   11  170
172 |-- 176   4  0.20   15  174
176 --| 180   5  0.25   20  178

**Calculando as Medidas de Posição Central**


#### Média

<p style="font-family: 	Times New Roman; font-size: 16px;">Para dados agrupados com intervalo de classe é necessário calcular para cada classe o ponto médio dado por $x_i = \frac{li + ls}{2}$ e depois proceder da mesma forma que para dados agrupados sem intervalo de classe:</p>

### $$\bar{X} = \frac{\sum x_if_i}{\sum f_i}$$

In [15]:
def calcular_media(data):
    
    # Somatório do numerador
    s_numerador = 0
    for i in range(data.shape[0]):
        s_numerador += data["xi"][i] * data["fi"][i]
        
    # Soma do denominador
    s_denominador = 0
    for i in range(data.shape[0]):
        s_denominador += data["fi"][i]
        
    # Cálculo da média
    media = s_numerador / s_denominador
    return media

In [16]:
print(f"Média: {calcular_media(df)}")

Média: 170.4


#### Mediana

<p style="font-family: 	Times New Roman; font-size: 16px;">Para obtermos a mediana de um tabela de dados agrupados com intervalos de classes seguimos o seguinte procedimento:</p>

<p style="font-family: 	Times New Roman; font-size: 16px;">O primeiro passo é encontrar o valor $\frac{n}{2}$ e determinar qual é a classe que representa a mediana. Após ser determinada a classe que contém a mediana, aplica-se a seguinte equação:</p>

### $$M_e(X) = l_{iMe} + \left[\frac{\frac{n}{2} - \sum f_{iant}}{f_{iMe}}\right]h$$

Onde:

- $l_{iMe}$ - Limite inferior da classe que contém a mediana.

- $\sum f_{iant}$ - Soma das frequências anteriores à classe da mediana.

- $f_{iMe}$ - Frequência da classe que contém a mediana.

- $h$ - Amplitude do intervalo de classe.

In [17]:
# Obtendo a classe que contém a mediana
print(f"Classe da mediana está na frequência acumulada {20/2}")

Classe da mediana está na frequência acumulada 10.0


<p style="font-family: 	Times New Roman; font-size: 16px;">Ou seja, o valor da mediana está no intervalo de ($168 |-- 172$). Agora que encontramos a classe da mediana, aplicamos a fórmula mostrada acima.</p>

In [19]:
# Obtendo a mediana
Me = 168 + ((20/2 - 7) / 4) * 3

# Imprimindo o valor da mediana
print(f"Mediana: {Me}")

Mediana: 170.25


#### Moda

<p style="font-family: 	Times New Roman; font-size: 16px;">Para obtermos a moda de um tabela de dados agrupados com intervalos de classes seguimos o seguinte procedimento:</p>

- 1 - Detectar a classe que possui a maior frequência absoluta

- 2 - Aplicar a seguinte fórmula:

### $$M_o(X) = l_{iMo} + \left[ \frac{\Delta_1}{\Delta_1 + \Delta_2}\right]h$$

In [20]:
def Mo(liMo, delta1, delta2, h):
    
    # Cálculo da Moda
    mo = (liMo + ((delta1 / (delta1 + delta2)) * h))
    
    # Retornando o valor da Moda
    return mo

<div class="alert alert-block alert-info">
<b>Observação:</b> Note que na tabela de distribuição de frequência temos duas modas. Sendo assim, temos uma distribuição bimodal, logo teremos que calcular o valor de duas modas.
</div>


In [21]:
# Definindo os valores dos parâmetro para o cálculo da moda

# Parâmetro para a obtênção da primeira moda
liMo1   = 160
delta11 = 5
delta21 = 3
h       = 4

# Parâmetros para a obtênção da segunda moda
liMo2   = 176
delta12 = 1
delta22 = 5
h       = 4

In [23]:
# Chamando a função Mo
print(f"Primeira Moda: {Mo(liMo1, delta11, delta21, h):.2f}")
print(f"Segunda Moda: {Mo(liMo2, delta12, delta22, h):.2f}")

Primeira Moda: 162.50
Segunda Moda: 176.67
